### ISSUE TITLE
Complete the setting view

### ISSUE THREAD

**Issue by Migarve55** [Arquisoft/dechat_en1b#12]
The setting just have a placeholder now.
We need to create a basic interface, even if it is just the background and a message.

**Comment by Migarve55** [comment]
This is not really necessary, but we could add a button to add a friend in solid. At least this way we could add friends on the fly, without needing to edit our file.

**Comment by Nacho888** [comment]
Already implemented a basic form to add friend, maybe it need a few CSS tweeks but it seems to be functional.

**Comment by Migarve55** [comment]
We just need to change the view so it is more appealing and this issue should be done.
