### ISSUE TITLE
Implement chat synchronization between users 

### ISSUE THREAD

**Issue by Migarve55** [Arquisoft/dechat_en1b#19]
We need to see how to make the SOLID data synchronized between pods. 

For example: when I send a message, the other user chat should update, and vice versa.

**Comment by Migarve55** [comment]
We can use the updater like this:

```
   updater.addDownstreamChangeListener(doc, function () {
 	//Refresh the chat and what not
   });
```

I do not know if this will work in a folder, though.

**Comment by Migarve55** [comment]
It seems like SOLID is not implementing this functionality. We do not have a way to listen for changes, therefore we can not implement this functionality. 

Maybe we can use a timer.

**Comment by Nacho888** [comment]
Yeah, it's a good approach, I've done experiments with periodically self-calling functions to update certain parts but we have to do more research as it seems to execute the methods but not updating the data structures that are filled with the requests performed against SOLID.

**Comment by Migarve55** [comment]
I found [this](https://github.com/solid/solid-spec/blob/master/api-websockets.md).
We can use this to track changes.

**Comment by Migarve55** [comment]
Turns out that WebSocket is the precise thing the updater is using. We can make this work, no matter what we do. What a shame.
