### ISSUE TITLE
Research unique identifiers for messages

### ISSUE THREAD

**Issue by Migarve55** [Arquisoft/dechat_en1b#20]
We need to associate an UUID (Universal Unique Identifier) to the chat messages to make easier data managing.

**Comment by Nacho888** [comment]
We can use [this](https://github.com/kelektiv/node-uuid). Simply use `npm install uuid` and then, in our case, we can use `const uuidv1 = require('uuid/v1'); uuidv1(); // ⇨ '3b99e3e0-7598-11e8-90be-95472fb3ecbd'` to generate an UUID based on the timestamp of the message.
