### ISSUE TITLE
Refactor de navigation bar

### ISSUE THREAD

**Issue by Nacho888** [Arquisoft/dechat_en1b#24]
According to our design and to make it easier to use, we should modify the navigation bar following this points:

- [ ] Remove the "Chat" button, this view should be the default one if we are logged in.
- [ ] Move to a dropdown menu in the right part the following menu items in this order:
    * Profile
    * Settings (?)
    * Sign out
- [ ] Make the logo of the app to redirect to the main default view, the chat.
- [ ] Add an image for the menu

**Comment by StefanoDainelli** [comment]
I have done these three parts, but I added another issue for changing our dropdown menu in an image.

**Comment by Nacho888** [comment]
We will keep the previous version in the master, you can keep working on this if you want on a separated branch. Create a pull request when it's fully completed, but until now, it's a great try.
