### ISSUE TITLE
Make sure messages and friend refresh correctly

### ISSUE THREAD

**Issue by Nacho888** [Arquisoft/dechat_en1b#33]
- [x] Refresh friends when accessing "Chat" view
- [x] Refresh messages whenever we send a new one 
- [x] Refresh messages whenever the other user sends a new one (maybe polling every x amount of seconds...)

**Comment by Migarve55** [comment]
I have found a way to do this, I will try to fix it

**Comment by Nacho888** [comment]
I've implemented it used a "setInterval" every 15 seconds and changing some options in the rdf fetcher
