### ISSUE TITLE
Do the "Glossary" documentation 

### ISSUE THREAD

**Issue by Nacho888** [Arquisoft/dechat_en1b#6]
Do the twelfth part of the documentation following the arc42 framework.

Put any kind of concepts, links and so on, that you find interesting.

**Comment by Migarve55** [comment]
I'm on it

**Comment by Migarve55** [comment]
I have completed what I believe are  the basic terms, feel free to add more if you think that the glossary can be expanded.

**Comment by Migarve55** [comment]
One thing, the glossary should have the terms alphabetically ordered in order to increase readability.

**Comment by Nacho888** [comment]
Thank you! I didn't notice it :)
