### ISSUE TITLE
Final application deployed

### ISSUE THREAD

**Issue by labra** [Arquisoft/dechat_en1b#64]
I want to publish a web page collecting all the applications to share with Inrupt with a link to the application deployed and the technical documentation. 

The application deployed should be [here](https://arquisoft.github.io/dechat_en1b/) and from there it should be possible to go to the technical documentation.

Asuming that the technical documentation is [here](https://arquisoft.github.io/dechat_en1b/docs), it is not yet deployed.

Please, when you repair those links, send me a message to close this issue an add your application to the list of applications deployed.

**Comment by Nacho888** [comment]
I think this is already done 👍

**Comment by labra** [comment]
Thanks...I have added your app to the table
