### ISSUE TITLE
Figure how to convert Markdown documentation files to HTML

### ISSUE THREAD

**Issue by Nacho888** [Arquisoft/dechat_en1b#7]
We must find a script/funcionality to convert the actual pages of the documentation to a web page. Probably we are going to need to define:

* An index.md in the "/docs" folder to have links pointing to the other files. Something similiar as what has been done in the Wiki.
* Update the README.md to have some links to the documentation part.

Feel free to propose whatever you find.

**Comment by PabloFerMar** [comment]
[We could use pandoc](https://pandoc.org/). 
We are doing a presentation for this tool on friday in the seminar, but basically it can be used to convert our markdown pages to html-5.
In the pandoc webpage there are some examples and tutorials of how to use it, [and here´s a video of converting from markdown to html5](https://www.youtube.com/watch?v=sZBmoiFTJVY).

**Comment by Nacho888** [comment]
We have to take a look to pandoc, sounds great.

I have also found [this](https://github.com/showdownjs/showdown) utility that has a CLI to provide all the functionalities related with conversions, and a derived [version](https://github.com/showdownjs/ng-showdown) to AngularJS projects.

**Comment by Nacho888** [comment]
I was revising some other utilities, and we can have a look to [GitBook](https://www.gitbook.com/) and its [CLI tool](https://toolchain.gitbook.com/) to convert to HTML.
